# Generated by Django 4.0.6 on 2022-08-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('qr_gen_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodeevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='qrcodeevent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qrcodeevent',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='qrcodeevent',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='qrcodeevent',
            name='organizer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeevent',
            name='organizer_phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='qrcodeevent',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
