# Generated by Django 4.0.6 on 2022-08-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodebusiness',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qrcodebusiness',
            name='phone',
        ),
    ]
