# Generated by Django 4.0.6 on 2022-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avater',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(null=True),
        ),
    ]
