# Generated by Django 4.0.6 on 2022-08-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_avater_profile_avatar_profile_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='user',
        ),
    ]
