# Generated by Django 4.0.6 on 2022-08-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeevent',
            name='organizer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeevent',
            name='organizer_phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeevent',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
